-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: FINDB_PROD.CORE_BANKING
-- ============================================================

USE DATABASE FINDB_PROD;
USE SCHEMA CORE_BANKING;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "FINDB_PROD"."CORE_BANKING"."LEGACY_ACCOUNT_TYPES";

-- ------------------------------------------------------------
-- ALTER COLUMNS (pre-CREATE)
-- ------------------------------------------------------------

ALTER TABLE "FINDB_PROD"."CORE_BANKING"."CUSTOMERS" ADD COLUMN IF NOT EXISTS "MOBILE_APP_USER" BOOLEAN DEFAULT FALSE;
ALTER TABLE "FINDB_PROD"."CORE_BANKING"."CUSTOMERS" ADD COLUMN IF NOT EXISTS "DIGITAL_BANKING_TIER" VARCHAR(20);

-- ------------------------------------------------------------
-- ALTER SEQUENCES (pre-CREATE)
-- ------------------------------------------------------------

CREATE OR REPLACE SEQUENCE "FINDB_PROD"."CORE_BANKING"."SEQ_TRANSACTION_ID"
  START = 1000000
  INCREMENT = 1
  NOORDER
  COMMENT = 'Surrogate key for TRANSACTIONS';


-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE ACCOUNTS (
	ACCOUNT_ID NUMBER(12,0) NOT NULL DEFAULT FINDB_PROD.CORE_BANKING.SEQ_ACCOUNT_ID.NEXTVAL,
	ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	PRODUCT_ID NUMBER(8,0),
	BRANCH_ID NUMBER(6,0),
	ACCOUNT_TYPE VARCHAR(30) NOT NULL,
	ACCOUNT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
	CURRENT_BALANCE NUMBER(18,2) DEFAULT 0,
	AVAILABLE_BALANCE NUMBER(18,2) DEFAULT 0,
	INTEREST_RATE NUMBER(6,4),
	OPEN_DATE DATE,
	CLOSE_DATE DATE,
	LAST_ACTIVITY_DATE DATE,
	OVERDRAFT_LIMIT NUMBER(10,2) DEFAULT 0,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint UQ_ACCOUNT_NUM unique (ACCOUNT_NUMBER),
	constraint PK_ACCOUNTS primary key (ACCOUNT_ID),
	constraint FK_ACCT_CUSTOMER foreign key (CUSTOMER_ID) references FINDB_PROD.CORE_BANKING.CUSTOMERS(CUSTOMER_ID),
	constraint FK_ACCT_PRODUCT foreign key (PRODUCT_ID) references FINDB_PROD.CORE_BANKING.PRODUCTS(PRODUCT_ID),
	constraint FK_ACCT_BRANCH foreign key (BRANCH_ID) references FINDB_PROD.CORE_BANKING.BRANCHES(BRANCH_ID)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
  CHANGE_TRACKING = TRUE
COMMENT='Bank accounts — checking, savings, money market, CDs'
;

CREATE OR REPLACE TABLE RISK_SCORES (
	SCORE_ID NUMBER(12,0) NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	SCORE_TYPE VARCHAR(30) NOT NULL,
	SCORE_VALUE NUMBER(6,2) NOT NULL,
	SCORE_DATE DATE NOT NULL,
	MODEL_VERSION VARCHAR(20),
	RISK_BAND VARCHAR(10),
	FACTORS VARIANT,
	NEXT_REVIEW_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_RISK_SCORES primary key (SCORE_ID),
	constraint FK_RISK_CUSTOMER foreign key (CUSTOMER_ID) references FINDB_PROD.CORE_BANKING.CUSTOMERS(CUSTOMER_ID)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
  CHANGE_TRACKING = TRUE
COMMENT='DEV: ML-driven customer risk scores — pending PROD promotion after model sign-off'
;

CREATE OR REPLACE TABLE TRANSACTIONS cluster by (DATE_TRUNC('MONTH', TRANSACTION_DATE))(
	TRANSACTION_ID NUMBER(15,0) NOT NULL DEFAULT FINDB_PROD.CORE_BANKING.SEQ_TRANSACTION_ID.NEXTVAL,
	TRANSACTION_REF VARCHAR(40) NOT NULL,
	ACCOUNT_ID NUMBER(12,0) NOT NULL,
	TRANSACTION_TYPE VARCHAR(30) NOT NULL,
	AMOUNT NUMBER(18,4) NOT NULL,
	CURRENCY VARCHAR(3) DEFAULT 'USD',
	EXCHANGE_RATE NUMBER(10,6) DEFAULT 1,
	TRANSACTION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	VALUE_DATE DATE,
	DESCRIPTION VARCHAR(500),
	STATUS VARCHAR(20) DEFAULT 'POSTED',
	CHANNEL VARCHAR(30),
	MERCHANT_NAME VARCHAR(200),
	MERCHANT_CATEGORY VARCHAR(100),
	BALANCE_AFTER NUMBER(18,2),
	REVERSAL_OF NUMBER(15,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint UQ_TRANSACTION_REF unique (TRANSACTION_REF),
	constraint PK_TRANSACTIONS primary key (TRANSACTION_ID),
	constraint FK_TXN_ACCOUNT foreign key (ACCOUNT_ID) references FINDB_PROD.CORE_BANKING.ACCOUNTS(ACCOUNT_ID),
	constraint FK_TXN_REVERSAL foreign key (REVERSAL_OF) references FINDB_PROD.CORE_BANKING.TRANSACTIONS(TRANSACTION_ID)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
  CHANGE_TRACKING = TRUE
COMMENT='All financial transactions — DEV uses NUMBER(18,4) for FX/crypto precision'
;

CREATE OR REPLACE TABLE LOAN_PAYMENTS (
	PAYMENT_ID NUMBER(12,0) NOT NULL,
	LOAN_ID NUMBER(10,0) NOT NULL,
	PAYMENT_DATE DATE NOT NULL,
	DUE_DATE DATE,
	PAYMENT_AMOUNT NUMBER(12,2) NOT NULL,
	PRINCIPAL_PORTION NUMBER(12,2),
	INTEREST_PORTION NUMBER(12,2),
	ESCROW_PORTION NUMBER(12,2),
	LATE_FEE NUMBER(8,2) DEFAULT 0,
	PAYMENT_METHOD VARCHAR(30),
	PAYMENT_STATUS VARCHAR(20) DEFAULT 'COMPLETED',
	TRANSACTION_ID NUMBER(15,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_LOAN_PAYMENTS primary key (PAYMENT_ID),
	constraint FK_PMT_LOAN foreign key (LOAN_ID) references FINDB_PROD.CORE_BANKING.LOANS(LOAN_ID),
	constraint FK_PMT_TRANSACTION foreign key (TRANSACTION_ID) references FINDB_PROD.CORE_BANKING.TRANSACTIONS(TRANSACTION_ID)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
COMMENT='Loan payment history and amortization tracking'
;

CREATE OR REPLACE DYNAMIC TABLE DT_ACCOUNT_BALANCE_SUMMARY target_lag = '1 minute' warehouse = COMPUTE_WH
 COMMENT='Near-real-time account balance rollup — refreshed every minute'
  DATA_RETENTION_TIME_IN_DAYS = 1
  MAX_DATA_EXTENSION_TIME_IN_DAYS = 14
AS
SELECT
    A.ACCOUNT_ID,
    A.CUSTOMER_ID,
    A.ACCOUNT_NUMBER,
    A.ACCOUNT_TYPE,
    A.CURRENT_BALANCE                   AS BOOK_BALANCE,
    COALESCE(SUM(
        CASE
            WHEN T.TRANSACTION_TYPE IN ('DEPOSIT',    'CREDIT') THEN  T.AMOUNT
            WHEN T.TRANSACTION_TYPE IN ('WITHDRAWAL', 'DEBIT')  THEN -T.AMOUNT
            ELSE 0
        END
    ), 0)                               AS POSTED_ACTIVITY,
    COUNT(T.TRANSACTION_ID)             AS TRANSACTION_COUNT,
    MAX(T.TRANSACTION_DATE)             AS LAST_TRANSACTION_AT,
    CURRENT_TIMESTAMP()                 AS LAST_REFRESHED_AT
FROM ACCOUNTS A
LEFT JOIN TRANSACTIONS T
    ON  T.ACCOUNT_ID = A.ACCOUNT_ID
    AND T.STATUS     = 'POSTED'
    AND T.TRANSACTION_DATE >= DATEADD('day', -1, CURRENT_TIMESTAMP())
WHERE A.ACCOUNT_STATUS = 'ACTIVE'
GROUP BY A.ACCOUNT_ID, A.CUSTOMER_ID, A.ACCOUNT_NUMBER, A.ACCOUNT_TYPE, A.CURRENT_BALANCE;

CREATE OR REPLACE MATERIALIZED VIEW MV_DAILY_TRANSACTION_SUMMARY(
	TRANSACTION_DAY,
	ACCOUNT_ID,
	TRANSACTION_TYPE,
	TRANSACTION_COUNT,
	TOTAL_AMOUNT,
	AVG_AMOUNT,
	MIN_AMOUNT,
	MAX_AMOUNT
) as
SELECT
    DATE_TRUNC('DAY', TRANSACTION_DATE) AS TRANSACTION_DAY,
    ACCOUNT_ID,
    TRANSACTION_TYPE,
    COUNT(*)                            AS TRANSACTION_COUNT,
    SUM(AMOUNT)                         AS TOTAL_AMOUNT,
    AVG(AMOUNT)                         AS AVG_AMOUNT,
    MIN(AMOUNT)                         AS MIN_AMOUNT,
    MAX(AMOUNT)                         AS MAX_AMOUNT
FROM TRANSACTIONS
WHERE STATUS = 'POSTED'
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW V_CUSTOMER_ACCOUNT_SUMMARY(
	CUSTOMER_ID,
	CUSTOMER_NUMBER,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	CUSTOMER_STATUS,
	CREDIT_SCORE,
	MOBILE_APP_USER,
	DIGITAL_BANKING_TIER,
	TOTAL_ACCOUNTS,
	TOTAL_BALANCE,
	CHECKING_BALANCE,
	SAVINGS_BALANCE,
	MONEY_MARKET_BALANCE,
	LAST_ACTIVITY_DATE,
	BRANCH_ID,
	BRANCH_NAME,
	REGION
) as
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NUMBER,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.EMAIL,
    C.CUSTOMER_STATUS,
    C.CREDIT_SCORE,
    C.MOBILE_APP_USER,
    C.DIGITAL_BANKING_TIER,
    COUNT(A.ACCOUNT_ID)                                                    AS TOTAL_ACCOUNTS,
    SUM(A.CURRENT_BALANCE)                                                 AS TOTAL_BALANCE,
    SUM(CASE WHEN A.ACCOUNT_TYPE = 'CHECKING'     THEN A.CURRENT_BALANCE ELSE 0 END) AS CHECKING_BALANCE,
    SUM(CASE WHEN A.ACCOUNT_TYPE = 'SAVINGS'      THEN A.CURRENT_BALANCE ELSE 0 END) AS SAVINGS_BALANCE,
    SUM(CASE WHEN A.ACCOUNT_TYPE = 'MONEY_MARKET' THEN A.CURRENT_BALANCE ELSE 0 END) AS MONEY_MARKET_BALANCE,
    MAX(A.LAST_ACTIVITY_DATE)                                              AS LAST_ACTIVITY_DATE,
    C.BRANCH_ID,
    B.BRANCH_NAME,
    B.REGION
FROM CUSTOMERS C
LEFT JOIN ACCOUNTS A ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.ACCOUNT_STATUS = 'ACTIVE'
LEFT JOIN BRANCHES B ON B.BRANCH_ID   = C.BRANCH_ID
GROUP BY
    C.CUSTOMER_ID, C.CUSTOMER_NUMBER, C.FIRST_NAME, C.LAST_NAME,
    C.EMAIL, C.CUSTOMER_STATUS, C.CREDIT_SCORE, C.MOBILE_APP_USER, C.DIGITAL_BANKING_TIER,
    C.BRANCH_ID, B.BRANCH_NAME, B.REGION;

CREATE OR REPLACE PIPE "FINDB_PROD"."CORE_BANKING"."PIPE_TRANSACTION_INGEST"
  AUTO_INGEST = FALSE
  COMMENT = 'Snowpipe for bulk transaction CSV ingestion from STG_TRANSACTION_UPLOADS'
AS
COPY INTO TRANSACTIONS (
    TRANSACTION_REF, ACCOUNT_ID, TRANSACTION_TYPE,
    AMOUNT, CURRENCY, TRANSACTION_DATE, DESCRIPTION, CHANNEL, STATUS
)
FROM (
    SELECT
        $1::VARCHAR(40),
        $2::NUMBER(12),
        $3::VARCHAR(30),
        $4::NUMBER(18,4),
        COALESCE($5::VARCHAR(3), 'USD'),
        $6::TIMESTAMP_NTZ,
        $7::VARCHAR(500),
        $8::VARCHAR(30),
        'POSTED'
    FROM @STG_TRANSACTION_UPLOADS
)
FILE_FORMAT = (FORMAT_NAME = FF_CSV_TRANSACTIONS)
ON_ERROR    = 'CONTINUE';

CREATE OR REPLACE STREAM "FINDB_PROD"."CORE_BANKING"."STR_TRANSACTIONS_CDC"
ON TABLE "FINDB_PROD"."CORE_BANKING"."TRANSACTIONS"
APPEND_ONLY = FALSE
COMMENT = 'CDC stream on TRANSACTIONS for real-time fraud monitoring';

CREATE OR REPLACE STREAM "FINDB_PROD"."CORE_BANKING"."STR_ACCOUNTS_CHANGES"
ON TABLE "FINDB_PROD"."CORE_BANKING"."ACCOUNTS"
APPEND_ONLY = FALSE
COMMENT = 'Change stream on ACCOUNTS for balance audit trail and reconciliation';


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER FILE FORMAT "FINDB_PROD"."CORE_BANKING"."FF_CSV_TRANSACTIONS" SET
  COMMENT = 'CSV format for transaction batch files — DEV files include a header row'
  MULTI_LINE = FALSE
  SKIP_HEADER = 1;
ALTER STAGE "FINDB_PROD"."CORE_BANKING"."STG_TRANSACTION_UPLOADS" SET
  COMMENT = 'Internal stage for bulk transaction CSV uploads (ACH, wire, batch)';
ALTER TABLE "FINDB_PROD"."CORE_BANKING"."LOANS" ADD CONSTRAINT "FK_LOAN_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "FINDB_PROD"."CORE_BANKING"."ACCOUNTS" ("ACCOUNT_ID");
ALTER MASKING POLICY "FINDB_PROD"."CORE_BANKING"."MPL_MASK_SSN" SET COMMENT = 'SSN — tellers/loan officers/digital-banking: last-4 only; compliance/admin: full value';
ALTER MASKING POLICY "FINDB_PROD"."CORE_BANKING"."MPL_MASK_SSN" SET BODY ->
CASE
        WHEN CURRENT_ROLE() IN ('UCB_TELLER_ROLE', 'UCB_LOAN_OFFICER_ROLE', 'UCB_DIGITAL_BANKING_ROLE')
            THEN '***-**-' || RIGHT(VAL, 4)
        WHEN CURRENT_ROLE() IN ('UCB_COMPLIANCE_ROLE', 'UCB_ADMIN_ROLE', 'SYSADMIN')
            THEN VAL
        ELSE '***-**-****'
    END;
ALTER TABLE "FINDB_PROD"."CORE_BANKING"."CUSTOMERS" SET COMMENT = 'Customer master record — includes DEV digital-banking enrollment fields';
CREATE OR REPLACE PROCEDURE "FINDB_PROD"."CORE_BANKING"."SP_CALCULATE_INTEREST"("P_CALCULATION_DATE" DATE DEFAULT null)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS $$
DECLARE
    v_calc_date DATE;
BEGIN
    v_calc_date := COALESCE(:P_CALCULATION_DATE, CURRENT_DATE());

    -- Compound daily: balance × ((1 + rate/365)^1 − 1)
    MERGE INTO ACCOUNTS A
    USING (
        SELECT
            A2.ACCOUNT_ID,
            A2.CURRENT_BALANCE * (POWER(1 + IR.ANNUAL_RATE / 365.0, 1) - 1) AS DAILY_INTEREST
        FROM ACCOUNTS A2
        JOIN PRODUCTS P
            ON  P.PRODUCT_ID = A2.PRODUCT_ID
        JOIN INTEREST_RATES IR
            ON  IR.PRODUCT_CODE   = P.PRODUCT_CODE
            AND IR.EFFECTIVE_DATE <= :v_calc_date
            AND (IR.END_DATE IS NULL OR IR.END_DATE >= :v_calc_date)
        WHERE A2.ACCOUNT_STATUS = 'ACTIVE'
          AND A2.ACCOUNT_TYPE   IN ('SAVINGS', 'MONEY_MARKET', 'CD')
          AND A2.CURRENT_BALANCE > 0
    ) CALC ON (A.ACCOUNT_ID = CALC.ACCOUNT_ID)
    WHEN MATCHED THEN UPDATE SET
        A.CURRENT_BALANCE   = A.CURRENT_BALANCE   + CALC.DAILY_INTEREST,
        A.AVAILABLE_BALANCE = A.AVAILABLE_BALANCE + CALC.DAILY_INTEREST,
        A.UPDATED_AT        = CURRENT_TIMESTAMP();

    RETURN 'Compound interest accrual complete: ' || SQLROWCOUNT
           || ' accounts updated on ' || :v_calc_date;
END;
$$;

CREATE OR REPLACE PROCEDURE "FINDB_PROD"."CORE_BANKING"."SP_PROCESS_LOAN_PAYMENT"("P_LOAN_ID" NUMBER(38,0), "P_PAYMENT_AMOUNT" NUMBER(38,0), "P_PAYMENT_METHOD" VARCHAR DEFAULT 'ACH')
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS $$
DECLARE
    v_loan_balance   NUMBER;
    v_interest_rate  NUMBER;
    v_account_id     NUMBER;
    v_avail_balance  NUMBER;
    v_interest       NUMBER;
    v_principal      NUMBER;
    v_payment_id     NUMBER;
BEGIN
    SELECT OUTSTANDING_BALANCE, INTEREST_RATE, ACCOUNT_ID
    INTO   :v_loan_balance, :v_interest_rate, :v_account_id
    FROM   LOANS
    WHERE  LOAN_ID = :P_LOAN_ID AND LOAN_STATUS = 'CURRENT';

    -- DEV: overdraft guard — fail fast if insufficient funds
    SELECT AVAILABLE_BALANCE
    INTO   :v_avail_balance
    FROM   ACCOUNTS
    WHERE  ACCOUNT_ID = :v_account_id;

    IF (:v_avail_balance < :P_PAYMENT_AMOUNT) THEN
        RETURN 'ERROR: Insufficient funds — available $'
               || :v_avail_balance || ', required $' || :P_PAYMENT_AMOUNT;
    END IF;

    v_interest  := ROUND(:v_loan_balance * :v_interest_rate / 12.0, 2);
    v_principal := :P_PAYMENT_AMOUNT - :v_interest;

    SELECT COALESCE(MAX(PAYMENT_ID), 0) + 1
    INTO   :v_payment_id
    FROM   LOAN_PAYMENTS;

    INSERT INTO LOAN_PAYMENTS (
        PAYMENT_ID, LOAN_ID, PAYMENT_DATE, PAYMENT_AMOUNT,
        PRINCIPAL_PORTION, INTEREST_PORTION, PAYMENT_METHOD, PAYMENT_STATUS
    ) VALUES (
        :v_payment_id, :P_LOAN_ID, CURRENT_DATE(), :P_PAYMENT_AMOUNT,
        :v_principal, :v_interest, :P_PAYMENT_METHOD, 'COMPLETED'
    );

    UPDATE LOANS
    SET  OUTSTANDING_BALANCE = OUTSTANDING_BALANCE - :v_principal,
         LOAN_STATUS         = IFF(OUTSTANDING_BALANCE - :v_principal <= 0, 'PAID_OFF', 'CURRENT'),
         UPDATED_AT          = CURRENT_TIMESTAMP()
    WHERE LOAN_ID = :P_LOAN_ID;

    RETURN 'Payment $' || :P_PAYMENT_AMOUNT || ' applied to loan ' || :P_LOAN_ID
           || ' (principal $' || :v_principal || ', interest $' || :v_interest || ')';
END;
$$;

ALTER TASK "FINDB_PROD"."CORE_BANKING"."TSK_DAILY_INTEREST_CALC" SET
    SCHEDULE = 'USING CRON 0 0 * * * UTC',
    COMMENT = 'Runs SP_CALCULATE_INTEREST daily at midnight UTC';


-- ============================================================
-- END - 23 statement(s)
-- ============================================================